version: '3.8'

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - '9000:9000'
    depends_on:
      - mysql
  mysql:
    container_name: mysql
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - '${FORWARD_DB_PORT:-3307}:3306'
    environment:
        MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
        MYSQL_DATABASE: '${DB_DATABASE}'
        MYSQL_USER: '${DB_USERNAME}'
        MYSQL_PASSWORD: '${DB_PASSWORD}'
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - '8080:80'
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
      - mysql
  # node:
  #   image: node:14
  #   volumes:
  #     - .:/app
  #   working_dir: /app
  #   command: "npm install && npm run watch"
  # composer:
  #   container_name: composer
  #   image: composer/composer
  #   networks:
  #     - locastic
  #   ports:
  #     - "9001:9000"
  #   volumes:
  #     - "./composer:/composer"
  #   working_dir: /composer
  #   command: install

networks:
    locastic:
        driver: bridge
volumes:
    db_data:
        driver: local